// @vitest-environment jsdom
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { growthLabel, openGrowthEfficiency, openGrowthReportPreview } from './growth-efficiency-ui';
import type { BatchResult, SettingsCatalog, SimulationRequest, SimulationResult } from './types';
const steps = Array.from({length:15},(_,i)=>i+1);
const settingsTemplate = {overloadSteps:{atk:steps,ammo:steps},overloadFields:{atk:{label:'공격력'},ammo:{label:'장탄'}},characters:{A:{overload:{atk:2}}}} as unknown as SettingsCatalog;
let settings:SettingsCatalog;
beforeEach(()=>{localStorage.clear();settings=structuredClone(settingsTemplate);});
const request = {squad:['A'],characters:{A:{overload:{atk:2}}},duration:180,enemyDef:63000,enemyCode:'작열',corePx:52,hasParts:false,seed:42,rngMode:'expected',defenseRateWindows:[{start:30,end:60,rate:50}]} as unknown as SimulationRequest;
const batch = {total:100,decks:[{deckId:1,request,result:{squadTotal:100,charTotals:{A:100}}}]} as unknown as BatchResult;
const result = (n:number)=>({squadTotal:n,charTotals:{A:n}} as unknown as SimulationResult);
const close=()=>document.querySelector<HTMLButtonElement>('.growth-close')?.click();
afterEach(()=>{close();vi.restoreAllMocks();});
describe('growth efficiency dialog',()=>{
 it('persists per-character target options and levels across new sessions and resets them',()=>{
  const deps={settings,catalog:new Map(),deckName:()=> '덱 1',current:()=>({overloadLines:{머리:[{option:'atk',level:2}]}}),simulate:vi.fn()};
  openGrowthEfficiency(batch,deps);
  const pick=()=>document.querySelector<HTMLSelectElement>('select[aria-label="덱 1 A 머리 1번 목표 옵션"]')!;
  pick().value='ammo';pick().dispatchEvent(new Event('change'));
  const level=document.querySelector<HTMLSelectElement>('select[aria-label="덱 1 A 장탄 수치작 타협레벨"]')!;level.value='10';level.dispatchEvent(new Event('change'));
  close();const next=structuredClone(batch);next.decks[0]!.request.duration=60;openGrowthEfficiency(next,deps);
  expect(pick().value).toBe('ammo');
  expect(document.querySelector<HTMLSelectElement>('select[aria-label="덱 1 A 장탄 수치작 타협레벨"]')!.value).toBe('10');
  document.querySelector<HTMLButtonElement>('button[aria-label="덱 1 A 목표 옵션 리셋"]')!.click();
  expect(pick().value).toBe('atk');expect(localStorage.getItem('nikke-growth-target:v1:A')).toBeNull();
  expect(document.querySelector<HTMLSelectElement>('select[aria-label="덱 1 A 장탄 수치작 타협레벨"]')!.value).toBe('15');
 });
 it('restores targets and completed results on reopen without running simulations again',async()=>{
  HTMLElement.prototype.scrollIntoView=vi.fn();
  const simulate=vi.fn().mockResolvedValue(result(120));
  const deps={settings,catalog:new Map(),deckName:()=> '덱 1',current:()=>({overloadLines:{머리:[{option:'atk',level:2}]}}),simulate};
  openGrowthEfficiency(batch,deps);
  const skill=document.querySelector<HTMLSelectElement>('select[aria-label="덱 1 A 목표 스킬1"]')!;skill.value='7';skill.dispatchEvent(new Event('change'));
  document.querySelector<HTMLButtonElement>('.growth-primary')!.click();
  await vi.waitFor(()=>expect(document.querySelector('.growth-global-priority')).not.toBeNull());
  const output=document.querySelector('.growth-output')!.textContent;
  close();expect(document.querySelector('.growth-overlay')).toBeNull();
  openGrowthEfficiency(structuredClone(batch),deps);
  expect(document.querySelector('.growth-output')!.textContent).toBe(output);
  expect(document.querySelector<HTMLSelectElement>('select[aria-label="덱 1 A 목표 스킬1"]')!.value).toBe('7');
  expect(simulate).toHaveBeenCalledTimes(2);
  close();const different=structuredClone(batch);different.decks[0]!.request.duration=60;openGrowthEfficiency(different,deps);
  expect(document.querySelector('.growth-output')!.textContent).toBe('');
 });
 it('continues in-flight calculations while closed and restores the completed result',async()=>{
  const simulate=vi.fn().mockImplementationOnce(()=>new Promise<SimulationResult>(resolve=>{finish=resolve;})).mockResolvedValue(result(120));
  let finish!:(value:SimulationResult)=>void;
  const deps={settings,catalog:new Map(),deckName:()=> '덱 1',current:()=>({overloadLines:{머리:[{option:'atk',level:2}]}}),simulate};
  openGrowthEfficiency(batch,deps);document.querySelector<HTMLButtonElement>('.growth-primary')!.click();close();
  finish(result(100));await vi.waitFor(()=>expect(simulate).toHaveBeenCalledTimes(2));
  openGrowthEfficiency(batch,deps);
  await vi.waitFor(()=>expect(document.querySelector('.growth-status')?.textContent).toContain('100%'));
  expect(document.querySelector('.growth-global-priority')).not.toBeNull();
  expect(simulate).toHaveBeenCalledTimes(2);
 });
 it('uses the faster global ranking by default and computes deck synergy only on click',async()=>{
  HTMLElement.prototype.scrollIntoView=vi.fn();
  const many=structuredClone(batch);many.decks[0]!.request.squad=['A','B','C'];
  for(const name of ['B','C'])many.decks[0]!.request.characters![name]={overload:{atk:2}};
  const totals:Record<string,number>={'':100,A:120,B:110,C:115,AB:160,AC:140,BC:130,ABC:170};
  const simulate=vi.fn(async(request:SimulationRequest)=>result(totals[Object.entries(request.characters!).filter(([,v])=>v.overload?.atk===15).map(([k])=>k).sort().join('')]!));
  openGrowthEfficiency(many,{settings,catalog:new Map(),deckName:()=> '덱 1',current:()=>({overloadLines:{머리:[{option:'atk',level:2}]}}),simulate});
  const cost=document.querySelector<HTMLInputElement>('input[aria-label="모듈 가성비 분석"]')!;expect(cost.checked).toBe(true);cost.checked=false;cost.dispatchEvent(new Event('change'));
  document.querySelector<HTMLButtonElement>('.growth-primary')!.click();
  await vi.waitFor(()=>expect(document.querySelector('.growth-status')?.textContent).toContain('100% · 5/5회 완료'));
  expect(simulate).toHaveBeenCalledTimes(5);
  expect([...document.querySelectorAll('.growth-global-priority li strong')].map(el=>el.textContent)).toEqual(['덱 1 · A','덱 1 · C','덱 1 · B']);
  expect(document.querySelector('.growth-priority')).toBeNull();
  document.querySelector<HTMLButtonElement>('.growth-priority-button')!.click();
  await vi.waitFor(()=>expect(document.querySelector('.growth-status')?.textContent).toContain('100% · 2/2회 완료'));
  expect(simulate).toHaveBeenCalledTimes(7);
  expect([...document.querySelectorAll('.growth-priority li strong')].map(el=>el.textContent?.split(' · ')[0])).toEqual(['A','B','C']);
  expect(document.querySelector<HTMLProgressElement>('.growth-progress')!.value).toBe(100);
 });
 it('previews without downloading and downloads only on request, releasing the image when closed', () => {
  const create = vi.fn(()=>'blob:test'); const revoke = vi.fn();
  vi.stubGlobal('URL', {createObjectURL:create,revokeObjectURL:revoke});
  const click = vi.spyOn(HTMLAnchorElement.prototype,'click').mockImplementation(()=>{});
  const done = vi.fn(); const dismiss = openGrowthReportPreview(new Blob(['png']), done);
  expect(document.querySelector('.growth-report-image')?.getAttribute('src')).toBe('blob:test');
  expect(click).not.toHaveBeenCalled();
  document.querySelector<HTMLButtonElement>('.growth-report-dialog .growth-primary')!.click();
  expect(click).toHaveBeenCalledOnce();
  document.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape'}));
  expect(document.querySelector('.growth-report-overlay')).toBeNull();
  expect(revoke).toHaveBeenCalledWith('blob:test');
  dismiss(); expect(done).toHaveBeenCalledOnce(); vi.unstubAllGlobals();
 });
 it('labels personal gains and decreases accurately', () => {
  expect(growthLabel(100,120)).toBe('풀 육성 시 20.00% 상승');
  expect(growthLabel(100,80)).toBe('풀 육성 시 20.00% 감소');
  expect(growthLabel(0,80)).toContain('계산 불가');
  expect(growthLabel(100,120,1000)).toBe('풀 육성 시 20.00% 상승 · 총딜 대비 2.00% (20) 상승');
  expect(growthLabel(100,80,1000)).toContain('총딜 대비 2.00% (20) 감소');
  expect(growthLabel(0,80,1000)).toContain('총딜 대비 8.00% (80) 상승');
  expect(growthLabel(0,80,0)).toContain('총딜 대비 비율 계산 불가 (80) 상승');
 });
 it('recalculates both sides with the saved conditions and invalidates edited reports',async()=>{
  HTMLElement.prototype.scrollIntoView=vi.fn();
  const simulate=vi.fn().mockResolvedValueOnce(result(100)).mockResolvedValueOnce(result(120));
  openGrowthEfficiency(batch,{settings,catalog:new Map(),deckName:()=> '덱 1',current:()=>({overloadLines:{머리:[{option:'atk',level:2}]}}),simulate});
  expect(document.querySelectorAll('.growth-part')).toHaveLength(4);
  expect(document.querySelector<HTMLSelectElement>('.growth-line select')?.value).toBe('atk');
  document.querySelector<HTMLButtonElement>('.growth-primary')!.click();
  await vi.waitFor(()=>expect(document.querySelector('.growth-gain')?.textContent).toBe('+20.00%'));
  expect(simulate).toHaveBeenCalledTimes(2);
  expect(simulate.mock.calls[0]![0]).toEqual(request);
  expect(simulate.mock.calls[1]![0].defenseRateWindows).toEqual(request.defenseRateWindows);
  expect(simulate.mock.calls[1]![0].characters.A.overload).toEqual({atk:15});
  expect(batch.decks[0]!.request.characters!.A!.overload).toEqual({atk:2});
  const select=document.querySelector<HTMLSelectElement>('.growth-line select')!;select.value='ammo';select.dispatchEvent(new Event('change'));
  expect(document.querySelector('.growth-output')?.textContent).toBe('');
  expect(document.querySelector<HTMLButtonElement>('footer .growth-secondary')?.disabled).toBe(true);
 });
 it('requires acknowledgment for absent or stale part information',()=>{
  const simulate=vi.fn();
  openGrowthEfficiency(batch,{settings,catalog:new Map(),deckName:()=> '덱 1',current:()=>({overloadLines:{머리:[{option:'atk',level:4}]}}),simulate});
  expect(document.querySelector('.growth-character')?.textContent).toContain('부위 정보 없음');
  document.querySelector<HTMLButtonElement>('.growth-primary')!.click();
  expect(simulate).not.toHaveBeenCalled();
  expect(document.querySelector('.growth-status')?.textContent).toContain('확인란');
 });
 it('collapses excluded characters, preserves their build, and restores target controls',async()=>{
  HTMLElement.prototype.scrollIntoView=vi.fn();
  const simulate=vi.fn().mockResolvedValue(result(100));
  openGrowthEfficiency(batch,{settings,catalog:new Map(),deckName:()=> '덱 1',current:()=>undefined,simulate});
  const toggle=document.querySelector<HTMLButtonElement>('.growth-exclude')!;
  toggle.click();
  expect(document.querySelector<HTMLDetailsElement>('.growth-character')?.open).toBe(false);
  document.querySelector<HTMLButtonElement>('.growth-primary')!.click();
  await vi.waitFor(()=>expect(simulate).toHaveBeenCalledTimes(2));
  expect(simulate.mock.calls[1]![0].characters).toEqual(request.characters);
  expect(document.querySelector('.growth-output')?.textContent).toContain('육성 제외');
  expect(document.querySelector('.growth-output')?.textContent).not.toContain('옵션 괴리');
  expect(document.querySelector<HTMLSelectElement>('.growth-stage select')?.disabled).toBe(true);
  toggle.click();
  expect(document.querySelector<HTMLDetailsElement>('.growth-character')?.open).toBe(true);
  expect(document.querySelector<HTMLSelectElement>('.growth-stage select')?.disabled).toBe(false);
 });
 it('starts at the current breakthrough and sends the chosen target',async()=>{
  const configured=structuredClone(settings);
  configured.characters.A!.growthStage=2;
  configured.characters.A!.growthOptions=[{value:2,label:'2돌',affinity:30},{value:10,label:'코강 7',affinity:30}];
  const simulate=vi.fn().mockResolvedValue(result(100));
  openGrowthEfficiency(batch,{settings:configured,catalog:new Map(),deckName:()=> '덱 1',current:()=>({overloadLines:{머리:[{option:'atk',level:2}]}}),simulate});
  const stage=document.querySelector<HTMLSelectElement>('.growth-stage select')!;
  expect(stage.value).toBe('2'); stage.value='10';stage.dispatchEvent(new Event('change'));
  document.querySelector<HTMLButtonElement>('.growth-primary')!.click();
  await vi.waitFor(()=>expect(simulate).toHaveBeenCalledTimes(2));
  expect(simulate.mock.calls[1]![0].characters.A.growthStage).toBe(10);
  expect(document.querySelector('.growth-output')?.textContent).toContain('목표 코강 7');
 });
 it('clears incomplete comparisons after failure',async()=>{
  const simulate=vi.fn().mockResolvedValueOnce(result(100)).mockRejectedValueOnce(new Error('시험 오류'));
  openGrowthEfficiency(batch,{settings,catalog:new Map(),deckName:()=> '덱 1',current:()=>({overloadLines:{머리:[{option:'atk',level:2}]}}),simulate});
  document.querySelector<HTMLButtonElement>('.growth-primary')!.click();
  await vi.waitFor(()=>expect(document.querySelector('.growth-status')?.textContent).toContain('시험 오류'));
  expect(document.querySelector<HTMLButtonElement>('footer .growth-secondary')?.disabled).toBe(true);
  expect(document.querySelector<HTMLSelectElement>('.growth-line select')?.disabled).toBe(false);
 });
 it('sends chosen skills, collection and equipment while preserving the current build',async()=>{
  const configured=structuredClone(settings); configured.collectionStages=['없음','SR0','SR15'];
  configured.characters.A!.collection={stage:'SR0',favorite:0};
  configured.characters.A!.skillLevels={'1':4,'2':5,'3':6};
  const simulate=vi.fn().mockResolvedValue(result(100));
  openGrowthEfficiency(batch,{settings:configured,catalog:new Map(),deckName:()=> '덱 1',current:()=>({overloadLines:{머리:[{option:'atk',level:2}]}}),simulate});
  const select=(label:string,value:string)=>{const el=document.querySelector<HTMLSelectElement>(`select[aria-label="덱 1 A ${label}"]`)!;el.value=value;el.dispatchEvent(new Event('change'));};
  expect(document.querySelector<HTMLSelectElement>('select[aria-label="덱 1 A 목표 스킬1"]')!.value).toBe('4');
  select('목표 스킬1','10');select('목표 스킬2','9');select('목표 버스트','8');select('목표 소장품','stage:SR15');select('머리 목표 장비레벨','3');
  document.querySelector<HTMLButtonElement>('.growth-primary')!.click();
  await vi.waitFor(()=>expect(simulate).toHaveBeenCalledTimes(2));
  expect(simulate.mock.calls[1]![0].characters.A).toMatchObject({skillLevels:{'1':10,'2':9,'3':8},collection:{stage:'SR15',favorite:0},equipLevels:{머리:3}});
  expect(simulate.mock.calls[0]![0]).toEqual(request);
 });
});

it('keeps browser calculation but exposes no external engine exchange',()=>{
 openGrowthEfficiency(batch,{settings,catalog:new Map(),deckName:()=> '덱 1',current:()=>({overloadLines:{머리:[{option:'atk',level:2}]}}),simulate:vi.fn()});
 expect(document.querySelector('.growth-external')).toBeNull();
 expect(document.querySelector('textarea[aria-label="외부 계산 프롬프트"]')).toBeNull();
 expect(document.querySelector('a[download]')).toBeNull();
 expect(document.querySelector('.growth-primary')!.textContent).toBe('계산하기');
});
it('applies line counts immediately without compromise or apply buttons',()=>{
 const currentLines={머리:[{option:'atk',level:2}]};
 openGrowthEfficiency(batch,{settings,catalog:new Map(),deckName:()=> '덱 1',current:()=>({overloadLines:currentLines}),simulate:vi.fn()});
 const count=document.querySelector<HTMLSelectElement>('select[aria-label="덱 1 A 공격력 목표 줄 수"]')!;count.value='4';count.dispatchEvent(new Event('change'));
 expect([...document.querySelectorAll<HTMLSelectElement>('.growth-line select')].filter(s=>s.value==='atk')).toHaveLength(4);
 expect(document.querySelector('select[aria-label*="타협 옵션"]')).toBeNull();
 expect(document.querySelector('.growth-goal-actions')).toBeNull();
 const slot=[...document.querySelectorAll<HTMLSelectElement>('.growth-line select')].find(s=>s.value==='atk')!;slot.value='ammo';slot.dispatchEvent(new Event('change'));
 expect(count.value).toBe('3');expect(document.querySelector<HTMLSelectElement>('select[aria-label="덱 1 A 장탄 목표 줄 수"]')!.value).toBe('1');
});

it('lets MCP read goals and run the same browser calculation without exporting code',async()=>{
 HTMLElement.prototype.scrollIntoView=vi.fn();
 const {inspectGrowthPlan,calculateGrowthPlan}=await import('./growth-mcp');
 const moduleClient=await import('./overload-cost-client');
 vi.spyOn(moduleClient,'analyzeModulePart').mockResolvedValue({levels:[15,15,15],currency:'modules',mode:'effects-first',target:['atk_pct','element_bonus','crit_dmg'],order:[0,1,2],effect:0,value:100,lock:3,change:100,total:103,keys:0,error95:1,samples:4000,unlocked:[]});
 const keys=['atk_pct','element_bonus','crit_dmg'];
 const fullSettings={...settingsTemplate,overloadSteps:Object.fromEntries(keys.map(k=>[k,steps])),overloadFields:Object.fromEntries(keys.map(k=>[k,{label:k}])),characters:{A:{overload:Object.fromEntries(keys.map(k=>[k,4]))}}} as unknown as SettingsCatalog;
 const lines=Object.fromEntries(['머리','몸통','팔','다리'].map(part=>[part,keys.map(option=>({option,level:1}))]));
 const saved=structuredClone(batch);saved.decks[0]!.request.characters={A:{overload:Object.fromEntries(keys.map(k=>[k,4])),overloadLines:lines}};
 const simulate=vi.fn().mockResolvedValue(result(120));
 openGrowthEfficiency(saved,{settings:fullSettings,catalog:new Map(),deckName:()=> '덱 1',current:()=>({overloadLines:lines}),simulate});
 const plan=inspectGrowthPlan();expect(plan.execution).toBe('user-browser');expect(plan).not.toHaveProperty('prompt');expect(plan).not.toHaveProperty('engineVersion');
 const answer=await calculateGrowthPlan();expect(answer.execution).toBe('user-browser');expect(simulate).toHaveBeenCalledTimes(3);expect(answer.modules).toHaveLength(1);
 expect(document.querySelector('.growth-cost-results')!.textContent).toContain('목표 옵션 12줄 찾기 0.0개');
 expect(document.querySelector('.growth-cost-results')!.textContent).toContain('목표 레벨 수치작 400.0개');
});

it('defaults value targets to 15 and applies individual and bulk thresholds to damage',async()=>{
 HTMLElement.prototype.scrollIntoView=vi.fn();const simulate=vi.fn().mockResolvedValue(result(120));
 openGrowthEfficiency(batch,{settings,catalog:new Map(),deckName:()=> '덱 1',current:()=>({overloadLines:{머리:[{option:'atk',level:2}]}}),simulate});
 const level=document.querySelector<HTMLSelectElement>('select[aria-label="덱 1 A 공격력 수치작 타협레벨"]')!;expect(level.value).toBe('15');
 level.value='8';level.dispatchEvent(new Event('change'));
 const {inspectGrowthPlan}=await import('./growth-mcp');expect((inspectGrowthPlan().decks as any)[0].characters[0].targetOverloadLines.머리[0].level).toBe(8);
 const bulk=document.querySelector<HTMLSelectElement>('select[aria-label="모든 수치작 타협레벨"]')!;bulk.value='10';bulk.dispatchEvent(new Event('change'));
 expect([...document.querySelectorAll<HTMLSelectElement>('.growth-goal-level')].every(select=>select.value==='10')).toBe(true);
 document.querySelector<HTMLButtonElement>('.growth-primary')!.click();await vi.waitFor(()=>expect(simulate).toHaveBeenCalledTimes(2));
 expect(simulate.mock.calls[1]![0].characters.A.overload.atk).toBe(10);
});
